#!/usr/bin/env bash
set -euo pipefail

### Config
LAN_DNS="192.168.0.4"
CLOUDFLARE_DNS="1.1.1.1 1.0.0.1"
TEST_NAME="nextcloud.mayer-it.net"   # internal name that should resolve via 192.168.0.4
DIG_TIMEOUT=2

### Helpers
have() { command -v "$1" >/dev/null 2>&1; }

default_iface() {
  # get interface that carries the default route (IPv4)
  ip route 2>/dev/null | awk '/^default/ {print $5; exit}'
}

nm_active_conn_for_iface() {
  local ifc="$1"
  nmcli -t -f NAME,DEVICE con show --active | awk -F: -v d="$ifc" '$2==d {print $1; exit}'
}


dns_up() {
  if have dig; then
    local ans
    ans=$(dig +time=${DIG_TIMEOUT} +tries=1 +short @"${LAN_DNS}" "${TEST_NAME}" A 2>/dev/null || true)
    
    # Check for actual IP address response, not error messages
    [[ "$ans" == "192.168.0.4" ]] && return 0
    
    # Only treat as success if we got a valid IP-like response
    if [[ -n "$ans" ]] && [[ "$ans" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      return 0
    fi
    
    return 1
  elif have nc; then
    nc -z -w ${DIG_TIMEOUT} "${LAN_DNS}" 53
    return $?
  else
    (exec 3<>/dev/tcp/"${LAN_DNS}"/53) 2>/dev/null && { exec 3>&-; return 0; }
    return 1
  fi
}

set_dns_nm() {
  local target="$1"
  local ifc conn
  ifc="$(default_iface)"
  [[ -n "$ifc" ]] || { echo "Could not determine default interface."; return 1; }
  conn="$(nm_active_conn_for_iface "$ifc")"
  [[ -n "$conn" ]] || { echo "No active NetworkManager connection for $ifc."; return 1; }

  echo "Using NetworkManager on connection \"$conn\" (iface: $ifc)"
  nmcli con mod "$conn" ipv4.dns "$target" ipv4.ignore-auto-dns yes
  nmcli con up "$conn" >/dev/null
  echo "Set IPv4 DNS to: $target"
}

set_dns_resolved() {
  local target="$1"
  local ifc
  ifc="$(default_iface)"
  [[ -n "$ifc" ]] || { echo "Could not determine default interface."; return 1; }

  echo "Using systemd-resolved on interface \"$ifc\""
  # Clear existing per-link DNS then set new
  resolvectl revert "$ifc" >/dev/null 2>&1 || true
  resolvectl dns "$ifc" "$target"
  resolvectl flush-caches >/dev/null 2>&1 || true
  echo "Set IPv4 DNS to: $target"
}

set_dns_resolvconf() {
  local target="$1"
  local file="/etc/resolv.conf"

  if [[ -L "$file" ]]; then
    echo "Warning: $file is a symlink (likely managed by systemd-resolved or resolvconf). Skipping direct edit."
    return 1
  fi

  echo "Writing $file directly"
  {
    echo "# Generated by check_dns.sh on $(date)"
    for ip in $target; do
      echo "nameserver $ip"
    done
  } > "$file"
  echo "Set nameservers to: $target"
}

apply_dns() {
  local target="$1"

  if have nmcli && systemctl is-active --quiet NetworkManager; then
    set_dns_nm "$target" && return 0
  fi

  if have resolvectl && systemctl is-active --quiet systemd-resolved; then
    set_dns_resolved "$target" && return 0
  fi

  set_dns_resolvconf "$target"
}

### Main
if dns_up; then
  echo "✅ DNS at ${LAN_DNS} is up. Switching to LAN DNS."
  apply_dns "$LAN_DNS"
else
  echo "⚠️  DNS at ${LAN_DNS} is unreachable. Falling back to Cloudflare."
  apply_dns "$CLOUDFLARE_DNS"
fi
